version: 0.2

env:
  variables:
    # CodeBuild sets CODEBUILD_CI=true, but most about everyone checks for CI=true
    CI: 'true'
    # Layer version; bump this when the "API" of the layer changes
    BASE_VERSION: '1.0.0'
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 137112412989.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - make build AMAZONLINUX_DOCKER_IMAGE=137112412989.dkr.ecr.${AWS_REGION}.amazonaws.com/amazonlinux:2
artifacts:
  files:
    - build/lambda_clamav_layer*.zip
  discard-paths: yes
  name: 'lambda_clamav_layer-${BASE_VERSION}-b${CODEBUILD_BUILD_NUMBER}.zip'
