version: 0.2

env:
  variables:
    # CodeBuild sets CODEBUILD_CI=true, but most about everyone checks for CI=true
    CI: 'true'
    # Layer MAJOR.MINOR version; bump this when the "API" of the layer changes
    # The build number from CodeBuild will be appended to this as the patch version, indicating "newerness".
    BASE_VERSION: '1.0'
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 137112412989.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - make build AMAZONLINUX_DOCKER_IMAGE=137112412989.dkr.ecr.${AWS_REGION}.amazonaws.com/amazonlinux:2
      # Rename the file to include a version number before CodeBuild picks it up
      - mv build/lambda_clamav_layer.zip build/lambda_clamav_layer-${BASE_VERSION}.${CODEBUILD_BUILD_NUMBER}.zip
artifacts:
  files:
    - build/lambda_clamav_layer*.zip
  discard-paths: yes
